version: '3'
volumes:
  data:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - data:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  fronted:
    image: nginx:1.16
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=to_be_overrided_sender
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes: 
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    networks: 
      - fila
    depends_on:
      - queue
      
      